"""GAMES (Trackman regular/scrimmage game) CSV parsing (pure, no network/DB).

``parse_game_csv`` renames the raw Trackman v3 game-export CSV's columns to
their GAMES DB table names via ``CSV_TO_GAMES`` (the only name difference is
``'Top/Bottom' -> 'Top.Bottom'``; every other CSV column already matches its
GAMES column name 1:1) and selects the columns present in ``GAMES_COLS``.

``GAMES_COLS`` is the 167-name intersection of the CSV's mapped columns and
the 175-column GAMES table; GAMES's other 8 columns (AreaNum/InZone/Zone/
AreaOfZone/Stuff/Runners/QC/PathQ) are derived/loader-set and simply absent
from this parser's output (NULL on insert). ``PitchUID`` is preserved
unchanged so a later loader can dedup on it.
"""
from __future__ import annotations

import pandas as pd

# Maps each of the 167 raw Trackman game-CSV column names to its GAMES DB
# column name. Identity for every column except the one known difference.
CSV_TO_GAMES: dict[str, str] = {
    "PitchNo": "PitchNo",
    "Date": "Date",
    "Time": "Time",
    "PAofInning": "PAofInning",
    "PitchofPA": "PitchofPA",
    "Pitcher": "Pitcher",
    "PitcherId": "PitcherId",
    "PitcherThrows": "PitcherThrows",
    "PitcherTeam": "PitcherTeam",
    "Batter": "Batter",
    "BatterId": "BatterId",
    "BatterSide": "BatterSide",
    "BatterTeam": "BatterTeam",
    "PitcherSet": "PitcherSet",
    "Inning": "Inning",
    "Top/Bottom": "Top.Bottom",  # only CSV/GAMES name difference
    "Outs": "Outs",
    "Balls": "Balls",
    "Strikes": "Strikes",
    "TaggedPitchType": "TaggedPitchType",
    "AutoPitchType": "AutoPitchType",
    "PitchCall": "PitchCall",
    "KorBB": "KorBB",
    "TaggedHitType": "TaggedHitType",
    "PlayResult": "PlayResult",
    "OutsOnPlay": "OutsOnPlay",
    "RunsScored": "RunsScored",
    "Notes": "Notes",
    "RelSpeed": "RelSpeed",
    "VertRelAngle": "VertRelAngle",
    "HorzRelAngle": "HorzRelAngle",
    "SpinRate": "SpinRate",
    "SpinAxis": "SpinAxis",
    "Tilt": "Tilt",
    "RelHeight": "RelHeight",
    "RelSide": "RelSide",
    "Extension": "Extension",
    "VertBreak": "VertBreak",
    "InducedVertBreak": "InducedVertBreak",
    "HorzBreak": "HorzBreak",
    "PlateLocHeight": "PlateLocHeight",
    "PlateLocSide": "PlateLocSide",
    "ZoneSpeed": "ZoneSpeed",
    "VertApprAngle": "VertApprAngle",
    "HorzApprAngle": "HorzApprAngle",
    "ZoneTime": "ZoneTime",
    "ExitSpeed": "ExitSpeed",
    "Angle": "Angle",
    "Direction": "Direction",
    "HitSpinRate": "HitSpinRate",
    "PositionAt110X": "PositionAt110X",
    "PositionAt110Y": "PositionAt110Y",
    "PositionAt110Z": "PositionAt110Z",
    "Distance": "Distance",
    "LastTrackedDistance": "LastTrackedDistance",
    "Bearing": "Bearing",
    "HangTime": "HangTime",
    "pfxx": "pfxx",
    "pfxz": "pfxz",
    "x0": "x0",
    "y0": "y0",
    "z0": "z0",
    "vx0": "vx0",
    "vy0": "vy0",
    "vz0": "vz0",
    "ax0": "ax0",
    "ay0": "ay0",
    "az0": "az0",
    "HomeTeam": "HomeTeam",
    "AwayTeam": "AwayTeam",
    "Stadium": "Stadium",
    "Level": "Level",
    "League": "League",
    "GameID": "GameID",
    "PitchUID": "PitchUID",
    "EffectiveVelo": "EffectiveVelo",
    "MaxHeight": "MaxHeight",
    "MeasuredDuration": "MeasuredDuration",
    "SpeedDrop": "SpeedDrop",
    "PitchLastMeasuredX": "PitchLastMeasuredX",
    "PitchLastMeasuredY": "PitchLastMeasuredY",
    "PitchLastMeasuredZ": "PitchLastMeasuredZ",
    "ContactPositionX": "ContactPositionX",
    "ContactPositionY": "ContactPositionY",
    "ContactPositionZ": "ContactPositionZ",
    "GameUID": "GameUID",
    "UTCDate": "UTCDate",
    "UTCTime": "UTCTime",
    "LocalDateTime": "LocalDateTime",
    "UTCDateTime": "UTCDateTime",
    "AutoHitType": "AutoHitType",
    "System": "System",
    "HomeTeamForeignID": "HomeTeamForeignID",
    "AwayTeamForeignID": "AwayTeamForeignID",
    "GameForeignID": "GameForeignID",
    "Catcher": "Catcher",
    "CatcherId": "CatcherId",
    "CatcherThrows": "CatcherThrows",
    "CatcherTeam": "CatcherTeam",
    "PlayID": "PlayID",
    "PitchTrajectoryXc0": "PitchTrajectoryXc0",
    "PitchTrajectoryXc1": "PitchTrajectoryXc1",
    "PitchTrajectoryXc2": "PitchTrajectoryXc2",
    "PitchTrajectoryYc0": "PitchTrajectoryYc0",
    "PitchTrajectoryYc1": "PitchTrajectoryYc1",
    "PitchTrajectoryYc2": "PitchTrajectoryYc2",
    "PitchTrajectoryZc0": "PitchTrajectoryZc0",
    "PitchTrajectoryZc1": "PitchTrajectoryZc1",
    "PitchTrajectoryZc2": "PitchTrajectoryZc2",
    "HitSpinAxis": "HitSpinAxis",
    "HitTrajectoryXc0": "HitTrajectoryXc0",
    "HitTrajectoryXc1": "HitTrajectoryXc1",
    "HitTrajectoryXc2": "HitTrajectoryXc2",
    "HitTrajectoryXc3": "HitTrajectoryXc3",
    "HitTrajectoryXc4": "HitTrajectoryXc4",
    "HitTrajectoryXc5": "HitTrajectoryXc5",
    "HitTrajectoryXc6": "HitTrajectoryXc6",
    "HitTrajectoryXc7": "HitTrajectoryXc7",
    "HitTrajectoryXc8": "HitTrajectoryXc8",
    "HitTrajectoryYc0": "HitTrajectoryYc0",
    "HitTrajectoryYc1": "HitTrajectoryYc1",
    "HitTrajectoryYc2": "HitTrajectoryYc2",
    "HitTrajectoryYc3": "HitTrajectoryYc3",
    "HitTrajectoryYc4": "HitTrajectoryYc4",
    "HitTrajectoryYc5": "HitTrajectoryYc5",
    "HitTrajectoryYc6": "HitTrajectoryYc6",
    "HitTrajectoryYc7": "HitTrajectoryYc7",
    "HitTrajectoryYc8": "HitTrajectoryYc8",
    "HitTrajectoryZc0": "HitTrajectoryZc0",
    "HitTrajectoryZc1": "HitTrajectoryZc1",
    "HitTrajectoryZc2": "HitTrajectoryZc2",
    "HitTrajectoryZc3": "HitTrajectoryZc3",
    "HitTrajectoryZc4": "HitTrajectoryZc4",
    "HitTrajectoryZc5": "HitTrajectoryZc5",
    "HitTrajectoryZc6": "HitTrajectoryZc6",
    "HitTrajectoryZc7": "HitTrajectoryZc7",
    "HitTrajectoryZc8": "HitTrajectoryZc8",
    "ThrowSpeed": "ThrowSpeed",
    "PopTime": "PopTime",
    "ExchangeTime": "ExchangeTime",
    "TimeToBase": "TimeToBase",
    "CatchPositionX": "CatchPositionX",
    "CatchPositionY": "CatchPositionY",
    "CatchPositionZ": "CatchPositionZ",
    "ThrowPositionX": "ThrowPositionX",
    "ThrowPositionY": "ThrowPositionY",
    "ThrowPositionZ": "ThrowPositionZ",
    "BasePositionX": "BasePositionX",
    "BasePositionY": "BasePositionY",
    "BasePositionZ": "BasePositionZ",
    "ThrowTrajectoryXc0": "ThrowTrajectoryXc0",
    "ThrowTrajectoryXc1": "ThrowTrajectoryXc1",
    "ThrowTrajectoryXc2": "ThrowTrajectoryXc2",
    "ThrowTrajectoryYc0": "ThrowTrajectoryYc0",
    "ThrowTrajectoryYc1": "ThrowTrajectoryYc1",
    "ThrowTrajectoryYc2": "ThrowTrajectoryYc2",
    "ThrowTrajectoryZc0": "ThrowTrajectoryZc0",
    "ThrowTrajectoryZc1": "ThrowTrajectoryZc1",
    "ThrowTrajectoryZc2": "ThrowTrajectoryZc2",
    "PitchReleaseConfidence": "PitchReleaseConfidence",
    "PitchLocationConfidence": "PitchLocationConfidence",
    "PitchMovementConfidence": "PitchMovementConfidence",
    "HitLaunchConfidence": "HitLaunchConfidence",
    "HitLandingConfidence": "HitLandingConfidence",
    "CatcherThrowCatchConfidence": "CatcherThrowCatchConfidence",
    "CatcherThrowReleaseConfidence": "CatcherThrowReleaseConfidence",
    "CatcherThrowLocationConfidence": "CatcherThrowLocationConfidence",
}

# The 167 GAMES columns this parser targets (every CSV_TO_GAMES value; all
# 167 raw CSV columns had a GAMES match, so none were dropped). GAMES's
# remaining 8 columns (AreaNum/InZone/Zone/AreaOfZone/Stuff/Runners/QC/
# PathQ) are derived/loader-set and are simply absent here (NULL on insert).
GAMES_COLS: list[str] = [
    "PitchNo", "Date", "Time", "PAofInning", "PitchofPA", "Pitcher",
    "PitcherId", "PitcherThrows", "PitcherTeam", "Batter", "BatterId",
    "BatterSide", "BatterTeam", "PitcherSet", "Inning", "Top.Bottom", "Outs",
    "Balls", "Strikes", "TaggedPitchType", "AutoPitchType", "PitchCall",
    "KorBB", "TaggedHitType", "PlayResult", "OutsOnPlay", "RunsScored",
    "Notes", "RelSpeed", "VertRelAngle", "HorzRelAngle", "SpinRate",
    "SpinAxis", "Tilt", "RelHeight", "RelSide", "Extension", "VertBreak",
    "InducedVertBreak", "HorzBreak", "PlateLocHeight", "PlateLocSide",
    "ZoneSpeed", "VertApprAngle", "HorzApprAngle", "ZoneTime", "ExitSpeed",
    "Angle", "Direction", "HitSpinRate", "PositionAt110X", "PositionAt110Y",
    "PositionAt110Z", "Distance", "LastTrackedDistance", "Bearing",
    "HangTime", "pfxx", "pfxz", "x0", "y0", "z0", "vx0", "vy0", "vz0", "ax0",
    "ay0", "az0", "HomeTeam", "AwayTeam", "Stadium", "Level", "League",
    "GameID", "PitchUID", "EffectiveVelo", "MaxHeight", "MeasuredDuration",
    "SpeedDrop", "PitchLastMeasuredX", "PitchLastMeasuredY",
    "PitchLastMeasuredZ", "ContactPositionX", "ContactPositionY",
    "ContactPositionZ", "GameUID", "UTCDate", "UTCTime", "LocalDateTime",
    "UTCDateTime", "AutoHitType", "System", "HomeTeamForeignID",
    "AwayTeamForeignID", "GameForeignID", "Catcher", "CatcherId",
    "CatcherThrows", "CatcherTeam", "PlayID", "PitchTrajectoryXc0",
    "PitchTrajectoryXc1", "PitchTrajectoryXc2", "PitchTrajectoryYc0",
    "PitchTrajectoryYc1", "PitchTrajectoryYc2", "PitchTrajectoryZc0",
    "PitchTrajectoryZc1", "PitchTrajectoryZc2", "HitSpinAxis",
    "HitTrajectoryXc0", "HitTrajectoryXc1", "HitTrajectoryXc2",
    "HitTrajectoryXc3", "HitTrajectoryXc4", "HitTrajectoryXc5",
    "HitTrajectoryXc6", "HitTrajectoryXc7", "HitTrajectoryXc8",
    "HitTrajectoryYc0", "HitTrajectoryYc1", "HitTrajectoryYc2",
    "HitTrajectoryYc3", "HitTrajectoryYc4", "HitTrajectoryYc5",
    "HitTrajectoryYc6", "HitTrajectoryYc7", "HitTrajectoryYc8",
    "HitTrajectoryZc0", "HitTrajectoryZc1", "HitTrajectoryZc2",
    "HitTrajectoryZc3", "HitTrajectoryZc4", "HitTrajectoryZc5",
    "HitTrajectoryZc6", "HitTrajectoryZc7", "HitTrajectoryZc8",
    "ThrowSpeed", "PopTime", "ExchangeTime", "TimeToBase", "CatchPositionX",
    "CatchPositionY", "CatchPositionZ", "ThrowPositionX", "ThrowPositionY",
    "ThrowPositionZ", "BasePositionX", "BasePositionY", "BasePositionZ",
    "ThrowTrajectoryXc0", "ThrowTrajectoryXc1", "ThrowTrajectoryXc2",
    "ThrowTrajectoryYc0", "ThrowTrajectoryYc1", "ThrowTrajectoryYc2",
    "ThrowTrajectoryZc0", "ThrowTrajectoryZc1", "ThrowTrajectoryZc2",
    "PitchReleaseConfidence", "PitchLocationConfidence",
    "PitchMovementConfidence", "HitLaunchConfidence", "HitLandingConfidence",
    "CatcherThrowCatchConfidence", "CatcherThrowReleaseConfidence",
    "CatcherThrowLocationConfidence",
]


def parse_game_csv(df: pd.DataFrame, *, source_file: str) -> pd.DataFrame:
    """Rename a raw Trackman game-export CSV's columns to GAMES names and
    select the columns present in ``GAMES_COLS``.

    Renames via ``CSV_TO_GAMES`` first (so ``Top/Bottom`` becomes
    ``Top.Bottom``), then selects whichever ``GAMES_COLS`` are present in
    the renamed frame -- dropping any extra/unexpected columns. Returns a
    copy; filters no rows. ``PitchUID`` is preserved unchanged so a later
    loader can dedup on it. ``source_file`` is accepted for interface
    symmetry with the eventual loader but not otherwise used by this pure
    parser.
    """
    renamed = df.rename(columns=CSV_TO_GAMES)
    cols = [c for c in GAMES_COLS if c in renamed.columns]
    return renamed[cols].copy()
